name: Bug report
description: Create a report to help us improve
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for submitting a bug report!

        Before submitting:
        1. Try searching the existing [issues](issues) and [discussions](discussions) to see if your issue has already been reported
        2. Try asking on [Discord](https://discordapp.com/invite/FFb9YFX)
        3. If you're reporting a security vulnerability, please disclose responsibly via our [bug bounty program](https://hedera.com/bounty)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what you did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run the program
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      description: What version of the software are you running?
      label: Version
      placeholder: v0.1.0
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      description: Which network(s) did the issue occur on?
      label: Hedera network
      multiple: true
      options:
        - mainnet
        - testnet
        - previewnet
        - other
    validations:
      required: true
