blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/steven-sheehy/argocd-example-apps/discussions
    about: Please ask and answer questions here.
  - name: Report
    url: https://hedera.com/bounty
    about: Security
