apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-dependency
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/steven-sheehy/argocd-example-apps.git
    path: helm-dependency
    targetRevision: HEAD
    helm:
      values: |
        wordpress:
          replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: integration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
