apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-dependency
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: wordpress=docker.io/ssheehy/wordpress
    argocd-image-updater.argoproj.io/wordpress.allow-tags: regexp:^master-.*
    argocd-image-updater.argoproj.io/wordpress.helm.image-name: wordpress.image.repository
    argocd-image-updater.argoproj.io/wordpress.update-strategy: latest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/steven-sheehy/argocd-example-apps.git
    path: helm-dependency
    targetRevision: HEAD
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: integration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
